### ISSUE TITLE
message content filter

### ISSUE THREAD

**Issue by Defelo** [PyDrocsid/cogs#110]
- [x] delete messages containing configured substrings
- [x] `bypass` permission
- [x] send alert
- [x] react with an "warning" emoji on not deleted, but flagged messages 
- [x] write documentation

**Comment by AlbertUnruh** [comment]
I wouldn't delete a message just by containing a substring.
If for example the substring `scam.com` is blacklisted a user can send a message like `Don't visit sites like scam.com, they scam you.` 'll be deleted.
I think it 'ld be a better solution to send an alert with a message-link to prevent deleting messages which where ok.
