### ISSUE TITLE
Allow subreddit prefix

### ISSUE THREAD

**Issue by Defelo** [PyDrocsid/cogs#127]
Allow usage of the `/r/` prefix for subreddits in `.reddit +` and `.reddit -`.

**Comment by umairkarel** [comment]
In which file we have make changes?

**Comment by Defelo** [comment]
> In which file we have make changes?

https://github.com/PyDrocsid/cogs/blob/develop/integrations/reddit/cog.py

**Comment by umairkarel** [comment]
Actually, I am not getting what changes we have to do?

**Comment by Defelo** [comment]
The function [`get_subreddit_name`](https://github.com/PyDrocsid/cogs/blob/develop/integrations/reddit/cog.py#L38) in line 38 takes the name of a subreddit and returns its display name. What should be changed is that if the parameter starts with the `/r/` or `r/` prefix, this prefix should be removed before putting it into the url in line 41.

**Comment by umairkarel** [comment]
Got it. I would like to do it. Please assign me this task.
