### ISSUE TITLE
Show join name in userlog

### ISSUE THREAD

**Issue by Defelo** [PyDrocsid/cogs#135]
Userlog "join" entries should contain the name the user had when joining the server.

**Comment by umairkarel** [comment]
Do we want to add `username` to the `out` list in this [function](https://github.com/PyDrocsid/cogs/blob/004d41016d10433e4e6f5436f60fb1f5ffc90c2a/information/user_info/cog.py#L249) ?

**Comment by TheCataliasTNT2k** [comment]
> Do we want to add `username` to the `out` list in this [function](https://github.com/PyDrocsid/cogs/blob/004d41016d10433e4e6f5436f60fb1f5ffc90c2a/information/user_info/cog.py#L249) ?

No, the logging cog currently logs all username and nickname changes. But it does not log the username the user had, when he joined the server.
Just log the username on join, that's all....
The current username can easily be found when pinging the user, no need to add it to `out`.

**Comment by umairkarel** [comment]
> Just log the username on join

Actually, I not getting how to Log?

**Comment by Defelo** [comment]
Actually, the username is already logged on join, but it is not shown in the userlog itself. Just read the name the user had on join from the database and put it into the userlog join entries (you will have to modify the translation string in translations/en.yml for this).

**Comment by umairkarel** [comment]
```python
join: Join
async for join in await db.stream(filter_by(Join, member=user_id)):
    username_on_join = t.ulog.username_on_join(join.member_name)
    out.append((join.timestamp, t.ulog.joined))
```

```yml
ulog:
  created: ":sparkles: **Created** this account."
  joined: ":tada: **Joined** this server."
  left: ":door: **Left** this server."
  username_on_join: "`{}`"
```

Is it right? added `username_on_join`

**Comment by Defelo** [comment]
You can just add the username placeholder to the `ulog.created` translation string instead of creating an new translation
