### ISSUE TITLE
Added "dont ask if something will work" to .fragestellung

### ISSUE THREAD

**Issue by Ari24-cb24** [PyDrocsid/cogs#164]
**Is your feature request related to a problem? Please describe.**
There are way too many people asking if something's going to work

**Describe the solution you'd like**
Added "dont ask if something will work" to .fragestellung and also append http://tryitands.ee to it as well

**Describe alternatives you've considered**
I dunno, just teach people different?

**Additional context**
nothin more

**Comment by Defelo** [comment]
Since `.fragestellung` is a custom command, please post your request in [`#feature-requests`](https://discord.com/channels/326817317075943424/347307502486159361).
